//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindSyncScope
{
    public class NorthwindOfflineEntityBase : object, Microsoft.Synchronization.Services.IOfflineEntity
    {
        private Microsoft.Synchronization.Services.OfflineEntityMetadata _serviceMetadata;

        public NorthwindOfflineEntityBase()
        {
            ServiceMetadata = new Microsoft.Synchronization.Services.OfflineEntityMetadata();
        }

        public virtual Microsoft.Synchronization.Services.OfflineEntityMetadata ServiceMetadata
        {
            get
            {
                return _serviceMetadata;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("value");
                }
                _serviceMetadata = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Products", TableLocalName = "[Products]", KeyFields = "ProductID")]
    public partial class Products : NorthwindOfflineEntityBase
    {
        private System.Guid _ProductID;

        private string _ProductName;

        private System.Nullable<System.Guid> _SupplierID;

        private System.Nullable<System.Guid> _CategoryID;

        private string _QuantityPerUnit;

        private System.Nullable<decimal> _UnitPrice;

        private System.Nullable<short> _UnitsInStock;

        private System.Nullable<short> _UnitsOnOrder;

        private System.Nullable<short> _ReorderLevel;

        private bool _Discontinued;

        public System.Guid ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                _ProductID = value;
            }
        }

        public string ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                _ProductName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.Guid> SupplierID
        {
            get
            {
                return _SupplierID;
            }
            set
            {
                _SupplierID = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.Guid> CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                _CategoryID = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string QuantityPerUnit
        {
            get
            {
                return _QuantityPerUnit;
            }
            set
            {
                _QuantityPerUnit = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<decimal> UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                _UnitPrice = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<short> UnitsInStock
        {
            get
            {
                return _UnitsInStock;
            }
            set
            {
                _UnitsInStock = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<short> UnitsOnOrder
        {
            get
            {
                return _UnitsOnOrder;
            }
            set
            {
                _UnitsOnOrder = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<short> ReorderLevel
        {
            get
            {
                return _ReorderLevel;
            }
            set
            {
                _ReorderLevel = value;
            }
        }

        public bool Discontinued
        {
            get
            {
                return _Discontinued;
            }
            set
            {
                _Discontinued = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Suppliers", TableLocalName = "[Suppliers]", KeyFields = "SupplierID")]
    public partial class Suppliers : NorthwindOfflineEntityBase
    {
        private System.Guid _SupplierID;

        private string _CompanyName;

        private string _ContactName;

        private string _ContactTitle;

        private string _Address;

        private string _City;

        private string _Region;

        private string _PostalCode;

        private string _Country;

        private string _Phone;

        private string _Fax;

        private string _HomePage;

        public System.Guid SupplierID
        {
            get
            {
                return _SupplierID;
            }
            set
            {
                _SupplierID = value;
            }
        }

        public string CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                _CompanyName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                _ContactName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ContactTitle
        {
            get
            {
                return _ContactTitle;
            }
            set
            {
                _ContactTitle = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Address
        {
            get
            {
                return _Address;
            }
            set
            {
                _Address = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string City
        {
            get
            {
                return _City;
            }
            set
            {
                _City = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Region
        {
            get
            {
                return _Region;
            }
            set
            {
                _Region = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                _PostalCode = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Country
        {
            get
            {
                return _Country;
            }
            set
            {
                _Country = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                _Phone = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                _Fax = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string HomePage
        {
            get
            {
                return _HomePage;
            }
            set
            {
                _HomePage = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Contacts", TableLocalName = "[Contacts]", KeyFields = "ContactID")]
    public partial class Contacts : NorthwindOfflineEntityBase
    {
        private System.Guid _ContactID;

        private string _ContactType;

        private string _CompanyName;

        private string _ContactName;

        private string _ContactTitle;

        private string _Address;

        private string _City;

        private string _Region;

        private string _PostalCode;

        private string _Country;

        private string _Phone;

        private string _Extension;

        private string _Fax;

        private string _HomePage;

        private string _PhotoPath;

        private byte[] _Photo;

        public System.Guid ContactID
        {
            get
            {
                return _ContactID;
            }
            set
            {
                _ContactID = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ContactType
        {
            get
            {
                return _ContactType;
            }
            set
            {
                _ContactType = value;
            }
        }

        public string CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                _CompanyName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                _ContactName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ContactTitle
        {
            get
            {
                return _ContactTitle;
            }
            set
            {
                _ContactTitle = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Address
        {
            get
            {
                return _Address;
            }
            set
            {
                _Address = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string City
        {
            get
            {
                return _City;
            }
            set
            {
                _City = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Region
        {
            get
            {
                return _Region;
            }
            set
            {
                _Region = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                _PostalCode = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Country
        {
            get
            {
                return _Country;
            }
            set
            {
                _Country = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                _Phone = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Extension
        {
            get
            {
                return _Extension;
            }
            set
            {
                _Extension = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                _Fax = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string HomePage
        {
            get
            {
                return _HomePage;
            }
            set
            {
                _HomePage = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string PhotoPath
        {
            get
            {
                return _PhotoPath;
            }
            set
            {
                _PhotoPath = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public byte[] Photo
        {
            get
            {
                return _Photo;
            }
            set
            {
                _Photo = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Customers", TableLocalName = "[Customers]", KeyFields = "CustomerID")]
    public partial class Customers : NorthwindOfflineEntityBase
    {
        private System.Guid _CustomerID;

        private string _CompanyName;

        private string _ContactName;

        private string _ContactTitle;

        private string _Address;

        private string _City;

        private string _Region;

        private string _PostalCode;

        private string _Country;

        private string _Phone;

        private string _Fax;

        public System.Guid CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                _CustomerID = value;
            }
        }

        public string CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                _CompanyName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                _ContactName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ContactTitle
        {
            get
            {
                return _ContactTitle;
            }
            set
            {
                _ContactTitle = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Address
        {
            get
            {
                return _Address;
            }
            set
            {
                _Address = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string City
        {
            get
            {
                return _City;
            }
            set
            {
                _City = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Region
        {
            get
            {
                return _Region;
            }
            set
            {
                _Region = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                _PostalCode = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Country
        {
            get
            {
                return _Country;
            }
            set
            {
                _Country = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                _Phone = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                _Fax = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Orders", TableLocalName = "[Orders]", KeyFields = "OrderID")]
    public partial class Orders : NorthwindOfflineEntityBase
    {
        private System.Guid _OrderID;

        private System.Nullable<System.Guid> _CustomerID;

        private System.Nullable<System.Guid> _EmployeeID;

        private System.Nullable<System.DateTime> _OrderDate;

        private System.Nullable<System.DateTime> _RequiredDate;

        private System.Nullable<System.DateTime> _ShippedDate;

        private System.Nullable<System.Guid> _ShipVia;

        private System.Nullable<decimal> _Freight;

        private string _ShipName;

        private string _ShipAddress;

        private string _ShipCity;

        private string _ShipRegion;

        private string _ShipPostalCode;

        private string _ShipCountry;

        public System.Guid OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                _OrderID = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.Guid> CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                _CustomerID = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.Guid> EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                _EmployeeID = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                _OrderDate = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.DateTime> RequiredDate
        {
            get
            {
                return _RequiredDate;
            }
            set
            {
                _RequiredDate = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.DateTime> ShippedDate
        {
            get
            {
                return _ShippedDate;
            }
            set
            {
                _ShippedDate = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.Guid> ShipVia
        {
            get
            {
                return _ShipVia;
            }
            set
            {
                _ShipVia = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<decimal> Freight
        {
            get
            {
                return _Freight;
            }
            set
            {
                _Freight = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipName
        {
            get
            {
                return _ShipName;
            }
            set
            {
                _ShipName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipAddress
        {
            get
            {
                return _ShipAddress;
            }
            set
            {
                _ShipAddress = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipCity
        {
            get
            {
                return _ShipCity;
            }
            set
            {
                _ShipCity = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipRegion
        {
            get
            {
                return _ShipRegion;
            }
            set
            {
                _ShipRegion = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipPostalCode
        {
            get
            {
                return _ShipPostalCode;
            }
            set
            {
                _ShipPostalCode = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipCountry
        {
            get
            {
                return _ShipCountry;
            }
            set
            {
                _ShipCountry = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Employees", TableLocalName = "[Employees]", KeyFields = "EmployeeID")]
    public partial class Employees : NorthwindOfflineEntityBase
    {
        private System.Guid _EmployeeID;

        private string _LastName;

        private string _FirstName;

        private string _Title;

        private string _TitleOfCourtesy;

        private System.Nullable<System.DateTime> _BirthDate;

        private System.Nullable<System.DateTime> _HireDate;

        private string _Address;

        private string _City;

        private string _Region;

        private string _PostalCode;

        private string _Country;

        private string _HomePhone;

        private string _Extension;

        private byte[] _Photo;

        private string _Notes;

        private System.Nullable<System.Guid> _ReportsTo;

        private string _PhotoPath;

        public System.Guid EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                _EmployeeID = value;
            }
        }

        public string LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                _LastName = value;
            }
        }

        public string FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                _FirstName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Title
        {
            get
            {
                return _Title;
            }
            set
            {
                _Title = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string TitleOfCourtesy
        {
            get
            {
                return _TitleOfCourtesy;
            }
            set
            {
                _TitleOfCourtesy = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return _BirthDate;
            }
            set
            {
                _BirthDate = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.DateTime> HireDate
        {
            get
            {
                return _HireDate;
            }
            set
            {
                _HireDate = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Address
        {
            get
            {
                return _Address;
            }
            set
            {
                _Address = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string City
        {
            get
            {
                return _City;
            }
            set
            {
                _City = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Region
        {
            get
            {
                return _Region;
            }
            set
            {
                _Region = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                _PostalCode = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Country
        {
            get
            {
                return _Country;
            }
            set
            {
                _Country = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string HomePhone
        {
            get
            {
                return _HomePhone;
            }
            set
            {
                _HomePhone = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Extension
        {
            get
            {
                return _Extension;
            }
            set
            {
                _Extension = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public byte[] Photo
        {
            get
            {
                return _Photo;
            }
            set
            {
                _Photo = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                _Notes = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.Guid> ReportsTo
        {
            get
            {
                return _ReportsTo;
            }
            set
            {
                _ReportsTo = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string PhotoPath
        {
            get
            {
                return _PhotoPath;
            }
            set
            {
                _PhotoPath = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Territories", TableLocalName = "[Territories]", KeyFields = "TerritoryID")]
    public partial class Territories : NorthwindOfflineEntityBase
    {
        private System.Guid _TerritoryID;

        private string _TerritoryDescription;

        private System.Guid _RegionID;

        public System.Guid TerritoryID
        {
            get
            {
                return _TerritoryID;
            }
            set
            {
                _TerritoryID = value;
            }
        }

        public string TerritoryDescription
        {
            get
            {
                return _TerritoryDescription;
            }
            set
            {
                _TerritoryDescription = value;
            }
        }

        public System.Guid RegionID
        {
            get
            {
                return _RegionID;
            }
            set
            {
                _RegionID = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Region", TableLocalName = "[Region]", KeyFields = "RegionID")]
    public partial class Region : NorthwindOfflineEntityBase
    {
        private System.Guid _RegionID;

        private string _RegionDescription;

        public System.Guid RegionID
        {
            get
            {
                return _RegionID;
            }
            set
            {
                _RegionID = value;
            }
        }

        public string RegionDescription
        {
            get
            {
                return _RegionDescription;
            }
            set
            {
                _RegionDescription = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Shippers", TableLocalName = "[Shippers]", KeyFields = "ShipperID")]
    public partial class Shippers : NorthwindOfflineEntityBase
    {
        private System.Guid _ShipperID;

        private string _CompanyName;

        private string _Phone;

        public System.Guid ShipperID
        {
            get
            {
                return _ShipperID;
            }
            set
            {
                _ShipperID = value;
            }
        }

        public string CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                _CompanyName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                _Phone = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Invoices", TableLocalName = "[Invoices]", KeyFields = "CustomerName,Salesperson,OrderID,ShipperName,ProductID,ProductName,UnitPrice,Quantity,Discount")]
    public partial class Invoices : NorthwindOfflineEntityBase
    {
        private string _CustomerName;

        private System.Guid _Salesperson;

        private System.Guid _OrderID;

        private string _ShipperName;

        private System.Guid _ProductID;

        private string _ProductName;

        private decimal _UnitPrice;

        private short _Quantity;

        private float _Discount;

        private string _ShipName;

        private string _ShipAddress;

        private string _ShipCity;

        private string _ShipRegion;

        private string _ShipPostalCode;

        private string _ShipCountry;

        private System.Nullable<System.Guid> _CustomerID;

        private string _Address;

        private string _City;

        private System.Nullable<System.Guid> _Region;

        private string _PostalCode;

        private string _Country;

        private System.Nullable<System.DateTime> _OrderDate;

        private System.Nullable<System.DateTime> _RequiredDate;

        private System.Nullable<System.DateTime> _ShippedDate;

        private System.Nullable<decimal> _ExtendedPrice;

        private System.Nullable<decimal> _Freight;

        public string CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                _CustomerName = value;
            }
        }

        public System.Guid Salesperson
        {
            get
            {
                return _Salesperson;
            }
            set
            {
                _Salesperson = value;
            }
        }

        public System.Guid OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                _OrderID = value;
            }
        }

        public string ShipperName
        {
            get
            {
                return _ShipperName;
            }
            set
            {
                _ShipperName = value;
            }
        }

        public System.Guid ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                _ProductID = value;
            }
        }

        public string ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                _ProductName = value;
            }
        }

        public decimal UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                _UnitPrice = value;
            }
        }

        public short Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                _Quantity = value;
            }
        }

        public float Discount
        {
            get
            {
                return _Discount;
            }
            set
            {
                _Discount = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipName
        {
            get
            {
                return _ShipName;
            }
            set
            {
                _ShipName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipAddress
        {
            get
            {
                return _ShipAddress;
            }
            set
            {
                _ShipAddress = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipCity
        {
            get
            {
                return _ShipCity;
            }
            set
            {
                _ShipCity = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipRegion
        {
            get
            {
                return _ShipRegion;
            }
            set
            {
                _ShipRegion = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipPostalCode
        {
            get
            {
                return _ShipPostalCode;
            }
            set
            {
                _ShipPostalCode = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string ShipCountry
        {
            get
            {
                return _ShipCountry;
            }
            set
            {
                _ShipCountry = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.Guid> CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                _CustomerID = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Address
        {
            get
            {
                return _Address;
            }
            set
            {
                _Address = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string City
        {
            get
            {
                return _City;
            }
            set
            {
                _City = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.Guid> Region
        {
            get
            {
                return _Region;
            }
            set
            {
                _Region = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                _PostalCode = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Country
        {
            get
            {
                return _Country;
            }
            set
            {
                _Country = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                _OrderDate = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.DateTime> RequiredDate
        {
            get
            {
                return _RequiredDate;
            }
            set
            {
                _RequiredDate = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<System.DateTime> ShippedDate
        {
            get
            {
                return _ShippedDate;
            }
            set
            {
                _ShippedDate = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<decimal> ExtendedPrice
        {
            get
            {
                return _ExtendedPrice;
            }
            set
            {
                _ExtendedPrice = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public System.Nullable<decimal> Freight
        {
            get
            {
                return _Freight;
            }
            set
            {
                _Freight = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "EmployeeTerritories", TableLocalName = "[EmployeeTerritories]", KeyFields = "EmployeeID,TerritoryID")]
    public partial class EmployeeTerritories : NorthwindOfflineEntityBase
    {
        private System.Guid _EmployeeID;

        private System.Guid _TerritoryID;

        public System.Guid EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                _EmployeeID = value;
            }
        }

        public System.Guid TerritoryID
        {
            get
            {
                return _TerritoryID;
            }
            set
            {
                _TerritoryID = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName = "Categories", TableLocalName = "[Categories]", KeyFields = "CategoryID")]
    public partial class Categories : NorthwindOfflineEntityBase
    {
        private System.Guid _CategoryID;

        private string _CategoryName;

        private string _Description;

        private byte[] _Picture;

        public System.Guid CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                _CategoryID = value;
            }
        }

        public string CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                _CategoryName = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Description
        {
            get
            {
                return _Description;
            }
            set
            {
                _Description = value;
            }
        }

        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public byte[] Picture
        {
            get
            {
                return _Picture;
            }
            set
            {
                _Picture = value;
            }
        }
    }

    [Microsoft.Synchronization.Services.SyncScopeAttribute()]
    public class NorthwindOfflineEntities
    {
        private System.Collections.Generic.ICollection<Products> _Productss;

        private System.Collections.Generic.ICollection<Suppliers> _Supplierss;

        private System.Collections.Generic.ICollection<Contacts> _Contactss;

        private System.Collections.Generic.ICollection<Customers> _Customerss;

        private System.Collections.Generic.ICollection<Orders> _Orderss;

        private System.Collections.Generic.ICollection<Employees> _Employeess;

        private System.Collections.Generic.ICollection<Territories> _Territoriess;

        private System.Collections.Generic.ICollection<Region> _Regions;

        private System.Collections.Generic.ICollection<Shippers> _Shipperss;

        private System.Collections.Generic.ICollection<Invoices> _Invoicess;

        private System.Collections.Generic.ICollection<EmployeeTerritories> _EmployeeTerritoriess;

        private System.Collections.Generic.ICollection<Categories> _Categoriess;
    }
}